# Generated by Django 4.2.13 on 2024-05-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prop_for_3d', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prop',
            old_name='author',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('approved_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessors_reply', to='prop_for_3d.prop')),
            ],
        ),
    ]
