# Generated by Django 4.2.13 on 2024-06-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop_for_3d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='keywords',
        ),
    ]
