# Generated by Django 4.2.13 on 2024-09-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prop_for_3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Decline', 'Decline'), ('-', '-')], default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='prop',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prop',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop_for_3d.supervisor'),
        ),
    ]
