# Generated by Django 4.2.13 on 2024-06-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop_for_3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted')], default=1),
        ),
    ]
