# Generated by Django 4.2.13 on 2024-06-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop_for_3d', '0002_rename_author_prop_student_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prop',
            options={'ordering': ['-created_on']},
        ),
    ]
